### ISSUE TITLE
Discussion - Modify labels to enhance issue management

### ISSUE THREAD

**Issue by CotSezer** [bounswe/bounswe2024group8#1]
Hello everyone,

I suppose some changes to manage effectively our issues. Firstly by adding type, status, and prioritization labels, we can look forward to our well-designed issue management.

1. By adding type labels, we can categorize issues based on their nature, such as bugs, maintenance, enhancements, or questions which will help us prioritize and address them accordingly.

2. With status labels, we can track the progress of each issue, from being open to being resolved or closed, ensuring that nothing falls through the cracks and that we maintain transparency about the state of our projects.

3. Prioritization labels will allow us to identify and handle high-priority issues first, ensuring that we address the most critical concerns and make the best use of our resources and time.

By implementing these changes, we can streamline our issue management process, making it more efficient and organized, and ultimately improving our overall project performance.

**Comment by CotSezer** [comment]
Great idea, maybe we can scale over 1-5? Any idea how to scale it?

**Comment by daghanerdonmez** [comment]
It would be great if we added descriptions to labels.

**Comment by erselcanakcili** [comment]
We can also create frontend, mobile, and backend labels.

**Comment by daghanerdonmez** [comment]
I've created a label called "Discussion". Suitable for issues like this one.

**Comment by daghanerdonmez** [comment]
Also created a "Wiki" label for issues related to our wiki page.

**Comment by yektaercul** [comment]
> Great idea, maybe we can scale over 1-5? Any idea how to scale it?

1-3 would be more concise I guess e.g.:
duration: short , duration: mid, duration: long

**Comment by yektaercul** [comment]
I think the labels are efficient and enough for our progress so I am closing the issue
