### ISSUE TITLE
Add Post and User Entities with Service and Controller Layers to backend

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#102]
### Issue Description

I will add User and Post entities with their service layer and controller layer implemented to the backend

### Issue Due Date

04/28/2024

### Reviewer

@oguzkagnici 

### Revision Due Date

04/28/2024

**Comment by oguzkagnici** [comment]
Post and User entities were well-structured and used throughout the whole backend development process. Closing the issue.
