### ISSUE TITLE
Add New Post Functionality to Frontend

### ISSUE THREAD

**Issue by cberko** [bounswe/bounswe2024group8#116]
### Issue Description

Implement a feature to allow users to add new posts through the frontend interface. This should include:

A form to input the post title and content.
Validation to ensure no fields are left empty.
Success message and form reset upon successful submission.

### Issue Due Date

29/04/2024

### Reviewer

@daghanerdonmez

### Revision Due Date

30/04/2024

**Comment by daghanerdonmez** [comment]
Not valid. Overhauled by @erselcanakcili at [here](https://github.com/bounswe/bounswe2024group8/issues/128)
