### ISSUE TITLE
Deploy Backend, Frontend and Databse to GCP

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#136]
### Issue Description

I will use my Dockerfiles to deploy Backend frontend and database to google cloud.

### Issue Due Date

04/30/2024

### Reviewer

@daghanerdonmez 

### Revision Due Date

04/30/2024

**Comment by yektaercul** [comment]
https://frontend-bjbpof6jaq-oa.a.run.app/
https://fanatic-backend-bjbpof6jaq-oa.a.run.app/
Both backend and frontend are deployed to these links

**Comment by daghanerdonmez** [comment]
Backend, frontend and database are now deployed in on GCP and can be accessed via links @yektaercul mentioned above. I am now closing this issue.
