### ISSUE TITLE
Write milestone 2 report 

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#142]
### Issue Description

I will write about the challenges we faced during the implementation of backend and how we handled them

### Issue Due Date

05/03/2024

### Reviewer

@edonmez01 

### Revision Due Date

05/03/2024

**Comment by yektaercul** [comment]
I have written the part about backend challenges and add them to our [report](https://github.com/bounswe/bounswe2024group8/wiki/Milestone-2-Report)

**Comment by edonmez01** [comment]
Seems well-written. Closing the issue.
