### ISSUE TITLE
Implement Like, Dislike and Bookmark for Posts

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#144]
### Issue Description

I will implement like, dislike and bookmark features for posts

### Issue Due Date

13/05/2024 23:00

### Reviewer

@yektaercul

### Revision Due Date

13/05/2024 23:00

**Comment by oguzkagnici** [comment]
Initial implementation is done. Waiting for review to finalize the structure.

**Comment by oguzkagnici** [comment]
Revised the whole structure. Added request and response payloads for reactions.

**Comment by oguzkagnici** [comment]
Completed the design. Created [Reaction](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/model/Reaction.java), [ReactionRequest](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/payload/ReactionRequest.java), [ReactionResponse](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/payload/ReactionResponse.java), [ReactionRepository](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/repository/ReactionRepository.java) classes.

**Comment by yektaercul** [comment]
All of the endpoints are working correctly. Needed refactors are made through Discord communication. Unit Tests are also written to test these endpoints. Well done.
