### ISSUE TITLE
Implement Comments

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#149]
### Issue Description

I will implement comment feature for posts

### Issue Due Date

16/05/2024 23:00

### Reviewer

@yektaercul

### Revision Due Date

16/05/2024 23:00

**Comment by oguzkagnici** [comment]
Implemented comment creation and reaction. Comments can be either liked or disliked.

**Comment by oguzkagnici** [comment]
Created [CommentService](Fixed createComment method in [CommentService](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/service/CommentService.java), [CommentController](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/controller/CommentController.java), [CommentRepository](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/repository/CommentRepository.java) classes.

**Comment by yektaercul** [comment]
Comments are tested with me through a Discord meeting everything was working correct. Also Unit Tests are available so everything was double-checked. Closing the issue
