### ISSUE TITLE
Add Community Service, Controller and Repository layers to backend

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#156]
### Issue Description

I will implement all of the community logic in the backend

### Issue Due Date

05/16/2024

### Reviewer

@oguzkagnici

### Revision Due Date

05/16/2024

**Comment by yektaercul** [comment]
All of the Community layer is implemented with the endpoints:
-getCommunityByName [controller](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/controller/CommunityController.java)
-getPostsOfCommunity [controller](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/controller/PostController.java)

**Comment by oguzkagnici** [comment]
Communities are properly working. Closing the issue...
