### ISSUE TITLE
Add User Profile Logic in backend

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#157]
### Issue Description

I will implement User profile logic with related shared posts, reacted posts and profile picture etc. I will write controller, service and repository layers.

### Issue Due Date

05/16/2024

### Reviewer

@oguzkagnici

### Revision Due Date

05/16/2024

**Comment by yektaercul** [comment]
Added 3 endpoints:
-getPostsOfUser [controller](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/controller/PostController.java)
-getPostsUserReactedTo [controller](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/controller/PostController.java)
-getUserById [controller](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/controller/UserController.java)

**Comment by oguzkagnici** [comment]
all endpoints mentioned above are fully functional. Closing the issue...
