### ISSUE TITLE
Create custom Post Response

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#158]
### Issue Description

I will create a new Post response Object to include the User specific infos: If he/she liked or bookmarked that post.
Also refactor and rewrite all of the repository methods related to them.

### Issue Due Date

05/16/2024

### Reviewer

@oguzkagnici

### Revision Due Date

05/16/2024

**Comment by yektaercul** [comment]
Created Custom PostResponse and implemented needed JPA Query methods [here](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/payload/PostResponse.java) and in the [repo](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/repository/PostRepository.java)

**Comment by oguzkagnici** [comment]
PostResponse is being used in various endpoints and successfully returns users' reactions and post content. Closing the issue...
