### ISSUE TITLE
Create Custom Comment Response

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#159]
### Issue Description

I will implement a Comment Response to include User specific statistics: If the user liked, disliked or bookmarked that post.
Also will update and rewrite new repository methods to return this object

### Issue Due Date

05/16/2024

### Reviewer

@oguzkagnici

### Revision Due Date

05/16/2024

**Comment by yektaercul** [comment]
Created Custom CommentResponse and implemented the needed JPA Queries [here](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/payload/CommentResponse.java)

**Comment by oguzkagnici** [comment]
CommentResponse is actively being used in our endpoints and seems to work. Closing the issue...
