### ISSUE TITLE
Implement Upload Profile Picture Endpoint in backend

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#161]
### Issue Description

I will configure the backend to store images and create a new endpoint to upload profile pictures for user. Also the User Model will be updated

### Issue Due Date

05/16/2024

### Reviewer

@oguzkagnici

### Revision Due Date

05/16/2024

**Comment by yektaercul** [comment]
Added Profile picture to User object and updated the return objects and added a new endpoint to update the profile picture.

**Comment by oguzkagnici** [comment]
Profile pictures in Users are properly working. Closing the issue...
