### ISSUE TITLE
Refactor Posting Posts to Add Images

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#162]
### Issue Description

I will refactor the Post Model and refactor the Post Create endpoint to accept images and return them when getting the posts.

### Issue Due Date

05/16/2024

### Reviewer

@oguzkagnici

### Revision Due Date

05/16/2024

**Comment by yektaercul** [comment]
Image acceptance added to the post objects. Also return of the posts updated accordingly [here](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/model/Post.java)

**Comment by oguzkagnici** [comment]
Images in posts are fully functional. Closing the issue...
