### ISSUE TITLE
Create Unit Tests For Comment Service

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#173]
### Issue Description

Writing several unit tests for CommentService class

### Issue Due Date

16/05/2024 23:00

### Reviewer

@yektaercul

### Revision Due Date

16/05/2024 23:00

**Comment by oguzkagnici** [comment]
Created [Tests](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/test/java/com/example/fanaticbackend/service/CommentServiceTest.java).

**Comment by yektaercul** [comment]
Unit tests are working great with an high percentage of coverage. Closing the issue.
