### ISSUE TITLE
Implement Like, Dislike Features for Comments

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#175]
### Issue Description

Implementing like and dislike reactions for comments

### Issue Due Date

16/05/2024 23:00

### Reviewer

@yektaercul

### Revision Due Date

16/05/2024 23:00

**Comment by oguzkagnici** [comment]
Implemented reactToComment Method in [CommentService](https://github.com/bounswe/bounswe2024group8/blob/dev/application/fanatic-backend/src/main/java/com/example/fanaticbackend/service/CommentService.java)

**Comment by yektaercul** [comment]
Like and Dislike are shown to me in a meeting in Discord and everything was working successfully. Unit tests are also available for this so good to go. Closing the issue no further improvements needed
