### ISSUE TITLE
Update use-case diagram

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#190]
### Issue Description

The use-case diagram that was initially designed before the second customer milestone has to be updated in order to be more in line with the final state of the project.

### Issue Due Date

19.05.2024, 01:00

### Reviewer

@daghanerdonmez

### Revision Due Date

19.05.2024, 12:00

**Comment by edonmez01** [comment]
Updated use case diagram: https://github.com/bounswe/bounswe2024group8/wiki/Final-Use-Case-Diagram

**Comment by daghanerdonmez** [comment]
Seems fine.
