### ISSUE TITLE
Update Requirements for the final Milestone

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#192]
### Issue Description

I will refactor our Requirements in accordnce with what we achieved to do.

### Issue Due Date

05/19/2024

### Reviewer

@erselcanakcili

### Revision Due Date

05/19/2024

**Comment by erselcanakcili** [comment]
Requirements are in their final form. Closing the issue.

**Comment by yektaercul** [comment]
Here is the updated [reqs](https://github.com/bounswe/bounswe2024group8/wiki/Final-Software-Requirements)
