### ISSUE TITLE
Add Test Information to Milestone

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#193]
### Issue Description

I will write the needed informations to test our application.

### Issue Due Date

05/19/2024

### Reviewer

@oguzkagnici

### Revision Due Date

05/19/2024

**Comment by yektaercul** [comment]
The Report is updated [here](https://github.com/bounswe/bounswe2024group8/wiki/Final-Milestone-Report)

**Comment by oguzkagnici** [comment]
Test Information part looks detailed  and well-prepared. Closing the issue
