### ISSUE TITLE
Creating own personal wiki pages

### ISSUE THREAD

**Issue by TurkerErdem99** [bounswe/bounswe2024group8#195]
### Issue Description

Assignees are supposed to create their own wiki pages and add these pages to the sidebar.

### Issue Due Date

24/09/2024 15:00

### Reviewer

@oguzkagnici

### Revision Due Date

24/09/2024 23:59

**Comment by TurkerErdem99** [comment]
I created my [wiki page](https://github.com/bounswe/bounswe2024group8/wiki/Huseyin-Turker-Erdem). Sidebar is also edited accordingly.

**Comment by oguzkagnici** [comment]
All new member pages seem to be done. Closing the issue...
