### ISSUE TITLE
Evaluate and Select Optimal 3D Viewing Framework for Front-End

### ISSUE THREAD

**Issue by AliAlperenSonmez** [bounswe/bounswe2024group8#201]
### Issue Description

For our 3D design and modeling information exchange forum, a core requirement is to enable users to view and interact with 3D models directly. Research and identify potential 3D viewing frameworks suitable for our front-end.

Key considerations:
- Support for various 3D file formats
- User interaction capabilities (e.g., zooming, panning, rotating)

Make a recommendation for the most suitable framework, providing a justification for the choice.

### Issue Due Date

07/10/2024

### Reviewer

@oguzkagnici

### Revision Due Date

06/10/2024

**Comment by TurkerErdem99** [comment]
For frontend, we decided to use the library in the link below:

[https://github.com/kovacsv/Online3DViewer](https://github.com/kovacsv/Online3DViewer)
