### ISSUE TITLE
Lab 2 Report preparation

### ISSUE THREAD

**Issue by TurkerErdem99** [bounswe/bounswe2024group8#205]
### Issue Description

The report of the lab 2 should be prepared and added to the wiki page of the project. Sidebar should be updated accordingly.

### Issue Due Date

01/10/2024 20:00

### Reviewer

@oguzkagnici

### Revision Due Date

01/10/2024 20:00

**Comment by TurkerErdem99** [comment]
Lab 2 report is prepared [here](https://github.com/bounswe/bounswe2024group8/wiki/Lab-2-Report). Sidebar is also edited accordingly.

**Comment by oguzkagnici** [comment]
Report looks well-prepared and informative. Closing the issue...
