### ISSUE TITLE
Refactoring README in the root directory.

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#206]
### Issue Description

Refactoring main README file to create a more informative landing page.

### Issue Due Date

03/10/2024 20:00

### Reviewer

@yektaercul

### Revision Due Date

03/05/2024 20:00

**Comment by oguzkagnici** [comment]
Updated [README](https://github.com/bounswe/bounswe2024group8/blob/main/README.md).

**Comment by AliAlperenSonmez** [comment]
Seems good. Closing the issue.
