### ISSUE TITLE
Creating Mockups

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#207]
### Issue Description

I will create mockup UI elements for web and mobile.

### Issue Due Date

15/10/2024 20:00

### Reviewer

@yektaercul

### Revision Due Date

15/10/2024 20:00

**Comment by oguzkagnici** [comment]
Created [mockups](https://github.com/bounswe/bounswe2024group8/wiki/Mockups) for 5 different views.

**Comment by oguzkagnici** [comment]
Added mockups for creating posts and viewing tournaments.

**Comment by yektaercul** [comment]
Seems well designed and explained, since closing the issue.
