### ISSUE TITLE
Cerating Scenarios

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2024group8#208]
### Issue Description

Creating detailed scenarios according to customer experience 

### Issue Due Date

14/10/2024 20:00

### Reviewer

@TurkerErdem99

### Revision Due Date

14/10/2024 20:00

**Comment by edonmez01** [comment]
Added a scenario detailing the use of challenges.

**Comment by tuluyhansozen** [comment]
Added the sceneario for Semantic Search and Filtering

**Comment by tuluyhansozen** [comment]
@TurkerErdem99 waiting for review Scenarios [(https://github.com/bounswe/bounswe2024group8/wiki/3Design-Scenarios)]
