### ISSUE TITLE
Creating Class Diagrams

### ISSUE THREAD

**Issue by AliAlperenSonmez** [bounswe/bounswe2024group8#209]
### Issue Description

- The class diagrams should be a clear visual representation of the system's structure.
- The class diagrams should cover the entire system, ensuring that all classes, attributes, methods, and relationships are accurately represented.

### Issue Due Date

15.10.2024

### Reviewer

@deniz6221

### Revision Due Date

14.10.2024

**Comment by AliAlperenSonmez** [comment]
I revised class diagram by adding methods to classes that @yektaercul created.

**Comment by tuluyhansozen** [comment]
I added tournamentmethods and seach class

**Comment by yektaercul** [comment]
Created the initial structure of class diagram [here](https://github.com/bounswe/bounswe2024group8/wiki/Class-Diagrams)

**Comment by AliAlperenSonmez** [comment]
Class diagram is created. Well done.
