### ISSUE TITLE
Creating Use Case Diagrams

### ISSUE THREAD

**Issue by erselcanakcili** [bounswe/bounswe2024group8#211]
### Issue Description

We are going to create use case diagrams to provide a visual representation of how users interact with our system.

### Issue Due Date

15/10/2024 23:59

### Reviewer

@oguzkagnici

### Revision Due Date

15/10/2024 19:59

**Comment by onurcerli** [comment]
Created the use case diagram. You can view from the link [use case diagram](https://github.com/bounswe/bounswe2024group8/wiki/Use-Case-Diagram). Added the link also to the sidebar in wikipage.

**Comment by onurcerli** [comment]
We reviewed it at the lab together with the team and also got feedback from the assistant. So, I updated the [use case diagram](https://github.com/bounswe/bounswe2024group8/wiki/Use-Case-Diagram) accordingly and it requires no further review.
