### ISSUE TITLE
Creating a milestone for first customer milestone

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#214]
### Issue Description

I am going to create a milestone to track our issues for the upcoming milestone.

### Issue Due Date

08/10/2024 20:00

### Reviewer

@yektaercul

### Revision Due Date

08/10/2024 20:00

**Comment by oguzkagnici** [comment]
Created [milestone](https://github.com/bounswe/bounswe2024group8/milestone/9).

**Comment by yektaercul** [comment]
Correctly created.
