### ISSUE TITLE
Creating Sequence Diagrams

### ISSUE THREAD

**Issue by deniz6221** [bounswe/bounswe2024group8#215]
### Issue Description

-The sequence diagrams should be a clear visual representation of the system's interactions.
-The sequence diagrams should cover key processes, ensuring that all objects, messages, and interactions are accurately represented over time.

### Issue Due Date

15/10/2024 00:00

### Reviewer

@erselcanakcili

### Revision Due Date

15/10/2024 00:00

**Comment by oguzkagnici** [comment]
Created the [draft](https://github.com/bounswe/bounswe2024group8/wiki/Sequence-Diagrams).
