### ISSUE TITLE
Writing Lab Report 3

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2024group8#216]
### Issue Description

Writing Lab Report 3 

### Issue Due Date

08/10/2024 20:00

### Reviewer

@deniz6221

### Revision Due Date

08/10/2024 20:00

**Comment by tuluyhansozen** [comment]
I completed the lab report https://github.com/bounswe/bounswe2024group8/wiki/Lab-3-Report

**Comment by tuluyhansozen** [comment]
I completed the lab report https://github.com/bounswe/bounswe2024group8/wiki/Lab-3-Report

**Comment by oguzkagnici** [comment]
Lab Report 3 seems complete. Closing the issue.
