### ISSUE TITLE
Writing Meeting Notes 4

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2024group8#218]
### Issue Description

Writing Meeting Notes 

### Issue Due Date

08/10/2024 20:00

### Reviewer

@erselcanakcili

### Revision Due Date

08/10/2024 20:00

**Comment by yektaercul** [comment]
Wrote the [page](https://github.com/bounswe/bounswe2024group8/wiki/Meeting-Notes-4-%E2%80%90-Oct-8)

**Comment by AliAlperenSonmez** [comment]
Seems good, closing the issue.
