### ISSUE TITLE
Discussion -  Adding branch names to the issues

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#22]
I think we should add branch names to issue titles related to software dev. This will enhance our codebase by providing a more concise and tidy branch management.  Imo this should done like this:

- We should label backend and frontend differently for e.g. : be-1 (backend), fe-1 (frontend) (besides dev, main and other important branches)
- Downside is, we should sort the related issues by creation time and find the last created branch and manually increment the last one by one and create the new branch with this name (e.g. be-45 (in case the last created one was the be-44)) to prevent duplicate branches

I want your opinions about this.

**Comment by yektaercul** [comment]
Or we can create the branch names according to the issue number e.g. : this issue is numbered 22 so if this were about the backend I would name my branch be-22.
This way there would be no duplicates since the issue numbers are unique

**Comment by umitcan07** [comment]
I recommend you Linear branch name convention :)
[Linear](https://linear.app/)

**Comment by yektaercul** [comment]
> I recommend you Linear branch name convention :) [Linear](https://linear.app/)

:) Yep, that's where I got the inspiration But I don't want to complicate things, just wanna keep it all in github.

**Comment by oguzkagnici** [comment]
We are going to proceed as discussed in the issue.
