### ISSUE TITLE
BE - Creating a Sign Up Page

### ISSUE THREAD

**Issue by erselcanakcili** [bounswe/bounswe2024group8#221]
### Issue Description

An endpoint for sign up page will be created in the backend.

### Issue Due Date

21/10/2024 23:59

### Reviewer

@oguzkagnici 

### Revision Due Date

21/10/2024 19:59

**Comment by yektaercul** [comment]
Added authorize endpoint [here](https://github.com/bounswe/bounswe2024group8/pull/239)

**Comment by oguzkagnici** [comment]
Necessary endpoints are implemented.
