### ISSUE TITLE
MB - Creating a Sign Up Page

### ISSUE THREAD

**Issue by erselcanakcili** [bounswe/bounswe2024group8#222]
### Issue Description

Sign up page will be implemented for mobile application.

### Issue Due Date

21/10/2024 23:59

### Reviewer

@edonmez01

### Revision Due Date

21/10/2024 19:59

**Comment by onurcerli** [comment]
Added the sign up screen to the mobile application. You can view it in [3design_mobile](https://github.com/bounswe/bounswe2024group8/tree/3design_mobile) branch.

**Comment by onurcerli** [comment]
The design needs review and also we need to handle backend integration after the backend is ready. So, the issue is not completed yet.

**Comment by AliAlperenSonmez** [comment]
I can see the sign-up page in expo, solid implementation. Backend integration will be another task.
