### ISSUE TITLE
Creating Database and Connecting it to Backend

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#224]
### Issue Description

Should implement the postgres database for backend and successfully connect it to backend in local environment.

### Issue Due Date

18/10/2024

### Reviewer

@oguzkagnici

### Revision Due Date

17/10/2024

**Comment by yektaercul** [comment]
Added the database connection codes with local configurations to the backend in [this](https://github.com/bounswe/bounswe2024group8/pull/239/commits) pull request.

**Comment by oguzkagnici** [comment]
Closing as complete
