### ISSUE TITLE
BE - Creating a Login Page 

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2024group8#225]
### Issue Description

An endpoint for login page will be created in the backend.

### Issue Due Date

21/10/2024 23:59

### Reviewer

@tuluyhansozen 

### Revision Due Date

21/10/2024 19:59

**Comment by yektaercul** [comment]
Added all of the authorization configurations, and implemented the endpoints with all corresponding parts. Can see the pull request [here](https://github.com/bounswe/bounswe2024group8/pull/239)

**Comment by tuluyhansozen** [comment]
Code reviewed
