### ISSUE TITLE
MB - Creating a Login Page

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2024group8#227]
### Issue Description

Login page will be implemented for mobile application.

### Issue Due Date

21/10/2024 23:59

### Reviewer

@AliAlperenSonmez

### Revision Due Date

21/10/2024 19:59

**Comment by onurcerli** [comment]
Added the login page to the mobile application. You can access it in [3design_mobile](https://github.com/bounswe/bounswe2024group8/tree/3design_mobile) branch.

**Comment by onurcerli** [comment]
The design needs review and also we need to handle backend integration after the backend is ready. So, the issue is not completed yet.

**Comment by AliAlperenSonmez** [comment]
The initial implementation seems solid

**Comment by AliAlperenSonmez** [comment]
commit d699e7993cba9d97782f680fcec5564e48de1e80 solved the issue.
