### ISSUE TITLE
Back-end Initialization and First-Time Setup

### ISSUE THREAD

**Issue by AliAlperenSonmez** [bounswe/bounswe2024group8#228]
### Issue Description

- Pushing the initialized and runnable project to the project repository.

### Issue Due Date

14.10.2024

### Reviewer

@erselcanakcili

### Revision Due Date

13.10.2024

**Comment by yektaercul** [comment]
Created the basic runnable code and merged it [here](https://github.com/bounswe/bounswe2024group8/pull/235)
