### ISSUE TITLE
FE - Make the home page display gallery and discussion posts

### ISSUE THREAD

**Issue by deniz6221** [bounswe/bounswe2024group8#231]
### Issue Description

Initialize a gallery and a discussion post interface. Create dummy objects and 3d models at first, use useEffect to store the dummy data into a state. Display them using array.map(). 

### Issue Due Date

19/10/2024 23:59

### Reviewer

@deniz6221

### Revision Due Date

19/10/2024 23:59

**Comment by erselcanakcili** [comment]
Added gallery post component and created feed.

**Comment by erselcanakcili** [comment]
Additionally, I've added the feature to display 3D objects.
