### ISSUE TITLE
FE - For Home Page Add The Create Post Dialog 

### ISSUE THREAD

**Issue by deniz6221** [bounswe/bounswe2024group8#232]
### Issue Description

Add a functioning dialog that lets users select a 3D Model, add a title and add the post content. Make it suitable for each category.

### Issue Due Date

19/10/2024 23:59

### Reviewer

@deniz6221

### Revision Due Date

19/10/2024 23:59

**Comment by tuluyhansozen** [comment]
Code reviewed and merged before first customer meeting
