### ISSUE TITLE
Researching applicable W3C standards: WAI-ARIA & WCAG

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#233]
### Issue Description

Conduct a research about W3C standards we are planning to implement.

### Issue Due Date

17/10/2024

### Reviewer

@erselcanakcili

### Revision Due Date

17/10/2024

**Comment by erselcanakcili** [comment]
We decided to use the [W3C Web Annotation Data Model](https://www.w3.org/TR/annotation-model/).
