### ISSUE TITLE
BE - Implement WikidataService for Semantic Search

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#244]
### Issue Description

Prepare SPARQL queries and implement Wikidata service for semantic search

### Issue Due Date

22/10/2024

### Reviewer

@yektaercul

### Revision Due Date

22/10/2024

**Comment by oguzkagnici** [comment]
Created [PR](https://github.com/bounswe/bounswe2024group8/pull/241) that contains the implementation

**Comment by yektaercul** [comment]
Examined the pr communicated with the Oguz and after some tests accepted the pr and merged it
