### ISSUE TITLE
Build apk file for mobile application

### ISSUE THREAD

**Issue by onurcerli** [bounswe/bounswe2024group8#248]
### Issue Description

Build the apk file for mobile application to be presented in the customer milestone

### Issue Due Date

21/10/2024

### Reviewer

@AliAlperenSonmez

### Revision Due Date

21/10/2024

**Comment by AliAlperenSonmez** [comment]
APK is generated, and works on android phone. Well done. https://github.com/bounswe/bounswe2024group8/pull/252
