### ISSUE TITLE
Writing first customer milestone report

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#254]
### Issue Description

I will write certain sections of the milestone report, as well as my contribution part.

### Issue Due Date

25/10/2024

### Reviewer

@erselcanakcili

### Revision Due Date

25/10/2024

**Comment by oguzkagnici** [comment]
I have created the template of [milestone report](https://github.com/bounswe/bounswe2024group8/wiki/First-Customer-Milestone-Report) and filled certain sections.

**Comment by tuluyhansozen** [comment]
I add customer feedback and reflections from first customer meeting notes
