### ISSUE TITLE
Frontend - Profile pages

### ISSUE THREAD

**Issue by TurkerErdem99** [bounswe/bounswe2024group8#261]
### Issue Description

Profile page should be implemented, where it provides all related requirements.

### Issue Due Date

19/11/2024 23:59

### Reviewer

@erselcanakcili

### Revision Due Date

19/11/2024 23:59

**Comment by uskudarli** [comment]
Issue descriptions should have considerably more detail in terms of the requirements and acceptance criteria.

**Comment by TurkerErdem99** [comment]
Updated description:

Profile page should be implemented, where the details/functionalities related to that user will be accessed.

If user goes to another user's profile page:
- [ ] Profile picture is shown
- [ ] Personal information is shown
- [ ] User can follow

If user goes to their own profile page:
- [ ] Profile picture is shown
- [ ] Personal information is shown
- [ ] User can change their username
- [ ] User can change password
- [ ] User can change their own profile picture
- [ ] User can delete their account

**Comment by erselcanakcili** [comment]
Completed essential features for Customer Milestone 2. Closing this issue for now..
