### ISSUE TITLE
Backend - Implement Reactions

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#269]
### Issue Description

I will be implementing post reactions (like, dislike, bookmark).

### Issue Due Date

12/05/2024

### Reviewer

@yektaercul

### Revision Due Date

12/05/2024

**Comment by oguzkagnici** [comment]
Implemented reaction features and opened [PR](https://github.com/bounswe/bounswe2024group8/pull/293).

**Comment by yektaercul** [comment]
Correctly working now on live
