### ISSUE TITLE
Backend - Implement Comments

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#270]
### Issue Description

I will be implementing comment feature for posts

### Issue Due Date

12/05/2024

### Reviewer

@yektaercul

### Revision Due Date

12/05/2024

**Comment by oguzkagnici** [comment]
Implemented comment feature and opened [PR](https://github.com/bounswe/bounswe2024group8/pull/273).

**Comment by yektaercul** [comment]
Design is very good,
