### ISSUE TITLE
Mobile - Implement post creation screen

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#288]
### Issue Description

The post creation screen for mobile has to be implemented. Users will be able to upload 3D models in their posts.

### Issue Due Date

12/11/2024 20:00

### Reviewer

@AliAlperenSonmez

### Revision Due Date

12/11/2024 20:00

**Comment by edonmez01** [comment]
The post creation screen is implemented and committed to to the Lab 6 branch.

**Comment by AliAlperenSonmez** [comment]
Seems good. Closing the issue
