### ISSUE TITLE
Implement gcp bucket file service

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#291]
### Issue Description

Implement file bucket service to upload files to gcp buckeet

### Issue Due Date

12/11/2024

### Reviewer

@tuluyhansozen

### Revision Due Date

13/11/2024

**Comment by yektaercul** [comment]
created the [pr](https://github.com/bounswe/bounswe2024group8/pull/290)

**Comment by tuluyhansozen** [comment]
Completed
