### ISSUE TITLE
Frontend and Mobile - Consistency Check for UI

### ISSUE THREAD

**Issue by TurkerErdem99** [bounswe/bounswe2024group8#292]
### Issue Description

As our team is asked for UI consistency between the mobile app and the frontend web, the consistency in the current versions of these products should be checked and revised accordingly. The following items should be considered to be consistent:

- Fonts and font sizes
- Color schema
- Layouts
- Item sizes (buttons, images, etc)

The user interfaces listed below should be checked:

- [ ] Login UI
- [ ] Signup UI
- [ ] Feed UI
- [ ] Feed for category UI
- [ ] Categories layout UI
- [ ] Create post UI
- [ ] Profile UI

### Issue Due Date

12/11/2024 18:30

### Reviewer

@yektaercul

### Revision Due Date

12/11/2024 18:30

**Comment by TurkerErdem99** [comment]
The necessary implementations on the frontend are committed [here](https://github.com/bounswe/bounswe2024group8/pull/295/commits/fb780a108d16139f2c305ede7db36bc7133d2440) and merged to main with [Lab 6 PR](https://github.com/bounswe/bounswe2024group8/pull/295).

**Comment by AliAlperenSonmez** [comment]
The necessary implementations on the mobile are done and merged to main with https://github.com/bounswe/bounswe2024group8/pull/295.
