### ISSUE TITLE
Lab6 report

### ISSUE THREAD

**Issue by AliAlperenSonmez** [bounswe/bounswe2024group8#297]
### Issue Description

Writing lab6 report and adding to project wiki

### Issue Due Date

12.11.2024

### Reviewer

@AliAlperenSonmez

### Revision Due Date

12.11.2024

**Comment by TurkerErdem99** [comment]
Lab 6 report is prepared in the [Lab 6 PR](https://github.com/bounswe/bounswe2024group8/pull/295). Meeting notes are [here](https://github.com/bounswe/bounswe2024group8/wiki/Meeting-Notes-7-%E2%80%90-Nov-12).
