### ISSUE TITLE
Backend- Implement tournament entering and scoring methods

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#308]
### Issue Description

I will add a method for tournament join and one method to update the score of the post in a tournament.

### Issue Due Date

15/11/2024

### Reviewer

@oguzkagnici

### Revision Due Date

16/11/2024

**Comment by yektaercul** [comment]
Written the code and created the [pr](https://github.com/bounswe/bounswe2024group8/pull/309)

**Comment by oguzkagnici** [comment]
Entry and scoring methods look functional. Closing...
