### ISSUE TITLE
Backend- Create the structure of tournaments

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#310]
### Issue Description

I will create whole tournament structure and add a scheduling structure for autonomous creation and finish of tournaments.

### Issue Due Date

15/11/2024

### Reviewer

@oguzkagnici

### Revision Due Date

16/11/2024

**Comment by yektaercul** [comment]
Written the code and created the  [pr](https://github.com/bounswe/bounswe2024group8/pull/309) with related commits [commit](https://github.com/bounswe/bounswe2024group8/pull/309/commits/d7651ad08cc32166d4d78f179f47512ad3a6cb1f)

**Comment by oguzkagnici** [comment]
Tournament feature works as intended. Closing...
