### ISSUE TITLE
Backend- Create Post 

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2024group8#311]
### Issue Description

Refinement of create post endpoint

### Issue Due Date

18/11/2024 

### Reviewer

@oguzkagnici

### Revision Due Date

21/11/2024

**Comment by tuluyhansozen** [comment]
https://github.com/bounswe/bounswe2024group8/pull/312
https://github.com/bounswe/bounswe2024group8/pull/310
implemented

**Comment by oguzkagnici** [comment]
Create post endpoint is properly working. Closing...
