### ISSUE TITLE
Mobile - Implement return to login button in register screen

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#318]
### Issue Description

In order to increase ease of use, a return to login button will be added to the register screen.

### Issue Due Date

19/11/2024 17:00

### Reviewer

@AliAlperenSonmez

### Revision Due Date

19/11/2024 17:00

**Comment by edonmez01** [comment]
Added the return to login button in the register screen.

**Comment by AliAlperenSonmez** [comment]
Seems good.
