### ISSUE TITLE
Backend - Implement web annotation model

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#324]
### Issue Description

Implementing web annotation model in accordance with W3C standard

### Issue Due Date

19/11/2024

### Reviewer

@oguzkagnici

### Revision Due Date

19/11/2024

**Comment by yektaercul** [comment]
Created [pr](https://github.com/bounswe/bounswe2024group8/pull/326)

**Comment by oguzkagnici** [comment]
Feature seems complete. Closing the issue.
