### ISSUE TITLE
Documentation of Software Quality Plan

### ISSUE THREAD

**Issue by TurkerErdem99** [bounswe/bounswe2024group8#328]
### Issue Description

The considerations about software qualty should be planned and documented.

### Issue Due Date

19/11/2024 20.00

### Reviewer

@TurkerErdem99

### Revision Due Date

19/11/2024 20.00

**Comment by tuluyhansozen** [comment]
I added overview

**Comment by TurkerErdem99** [comment]
The requirements of this issue seems to be done, well documented.
