### ISSUE TITLE
Demo Plan for Customer Milestone #2

### ISSUE THREAD

**Issue by TurkerErdem99** [bounswe/bounswe2024group8#329]
### Issue Description

The outline of the presentation for Customer Milestone #2 should be documented. The data population, the features and the scenario for the demo should be included.

### Issue Due Date

19/11/2024 20.00

### Reviewer

@oguzkagnici

### Revision Due Date

19/11/2024 20.00

**Comment by oguzkagnici** [comment]
I have prepared [plan](https://github.com/bounswe/bounswe2024group8/wiki/Customer-Milestone-2-Presentation-Outline)
