### ISSUE TITLE
Backend - Add followed users' posts to feed

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#349]
### Issue Description

I will be adding followed users' content to the feed

### Issue Due Date

26/11/2024

### Reviewer

@yektaercul

### Revision Due Date

26/11/2024

**Comment by oguzkagnici** [comment]
Created the [pr](https://github.com/bounswe/bounswe2024group8/pull/346)

**Comment by yektaercul** [comment]
Merged the pr everything seems well
