### ISSUE TITLE
Mobile - Connect feed page to backend

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#351]
### Issue Description

The feed page in the mobile app has to request posts from the backend and present them to the user. The system should filter the posts based on category. Also, the user should be able to toggle between visual and non-visual posts.

### Issue Due Date

25/11/2024 22:00

### Reviewer

@onurcerli

### Revision Due Date

25/11/2024 22:00

**Comment by edonmez01** [comment]
The feed page has been connected to backend, and the visual/non-visual post toggle has been implemented.

**Comment by onurcerli** [comment]
The application is tested after the backend integration and works properly.
