### ISSUE TITLE
Mobile - Implement follow category feature

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#354]
### Issue Description

In the mobile app, the follow category feature will be implemented. Users will be able to follow categories that they are interested in.

### Issue Due Date

25/11/2024 22:00

### Reviewer

@onurcerli

### Revision Due Date

25/11/2024 22:00

**Comment by edonmez01** [comment]
The feature has been implemented. Relevant pull request: #356

**Comment by onurcerli** [comment]
The feature works as intended. Closing the issue.
