### ISSUE TITLE
Mobile - Implement comments

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#357]
### Issue Description

The commenting feature will be implemented. Users should be able to comment on posts, and react on other users' comments.

### Issue Due Date

25/11/2024 22:00

### Reviewer

@onurcerli

### Revision Due Date

25/11/2024 22:00

**Comment by edonmez01** [comment]
The implementation of the feature is completed. Related pull request: #358

**Comment by onurcerli** [comment]
Tested the feature. It works as expected. Closing the issue.
