### ISSUE TITLE
Backend - Add new endpoint for PostResponse retrieval

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#361]
### Issue Description

I will implement an endpoint that returns post response object for a  single post.

### Issue Due Date

26/11/2024

### Reviewer

@yektaercul

### Revision Due Date

26/11/2024

**Comment by oguzkagnici** [comment]
Created getPostResponseByIdElseThrow endpoint.

**Comment by yektaercul** [comment]
Great work.
