### ISSUE TITLE
Mobile - Connect categories to backend

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#369]
### Issue Description

In the mobile app, the 3D model categories will be fetched from the backend instead of being stored statically. All the scripts in the app that use categories will be updated in accordance. 

### Issue Due Date

25/11/2024 22:00

### Reviewer

@onurcerli

### Revision Due Date

25/11/2024 22:00

**Comment by edonmez01** [comment]
The implementation has been completed. Related pull request: #370

**Comment by onurcerli** [comment]
It is implemented just fine. Categories are brought from the backend and there is no detected problem with the implementation. Closing the issue.
