### ISSUE TITLE
Mobile - Connect profile page to backend

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#372]
### Issue Description

The profile page in the mobile app will be connected to backend. The page will include the latest posts of the user.

### Issue Due Date

25/11/2024 22:00

### Reviewer

@onurcerli

### Revision Due Date

25/11/2024 22:00

**Comment by onurcerli** [comment]
It works as intended. The users can view their posts from their profile screen. Closing the issue.
