### ISSUE TITLE
Backend - Set up swagger on backend

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#377]
### Issue Description

I will implement swagger configurations and set up the file related endpoints accordingly.

### Issue Due Date

25/11/2024

### Reviewer

@oguzkagnici

### Revision Due Date

26/11/2024

**Comment by yektaercul** [comment]
Created the [pr](https://github.com/bounswe/bounswe2024group8/pull/376)

**Comment by oguzkagnici** [comment]
Reviewed the api doc from swagger api. Looks sufficient.
