### ISSUE TITLE
Mobile - Implementing Tournament Box

### ISSUE THREAD

**Issue by AliAlperenSonmez** [bounswe/bounswe2024group8#379]
### Issue Description

Tournament feture should be implemented to category feeds

### Issue Due Date

25/11/2024

### Reviewer

@onurcerli

### Revision Due Date

25/11/2024

**Comment by AliAlperenSonmez** [comment]
implementation is done.

**Comment by onurcerli** [comment]
Implementation is solid and works as intended.
