### ISSUE TITLE
Mobile - Implementing leaderboard screen

### ISSUE THREAD

**Issue by AliAlperenSonmez** [bounswe/bounswe2024group8#381]
### Issue Description

Implementing the leaderboard screen

### Issue Due Date

25/11/2024

### Reviewer

@onurcerli

### Revision Due Date

25/11/2024

**Comment by AliAlperenSonmez** [comment]
implementation is done.

**Comment by onurcerli** [comment]
The feature works well but we might later improve the design. For now, this is enough. Closing the issue.
