### ISSUE TITLE
Mobile - Connecting Leaderboard screen to backend

### ISSUE THREAD

**Issue by AliAlperenSonmez** [bounswe/bounswe2024group8#382]
### Issue Description

Connecting Leaderboard screen to backend

### Issue Due Date

25/11/2024

### Reviewer

@onurcerli

### Revision Due Date

25/11/2024

**Comment by AliAlperenSonmez** [comment]
implementation is done.

**Comment by onurcerli** [comment]
Tested the integration. It works properly. It fetches data when there exists any and handles edge cases such as when there is no tournaments, etc. Closing the issue.
