### ISSUE TITLE
Prepare a presentation scenario for customer milestone 2.

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#384]
### Issue Description

I will write a presentation flow for the second customer milestone 2.

### Issue Due Date

29/11/2024

### Reviewer

@yektaercul

### Revision Due Date

29/11/2024

**Comment by oguzkagnici** [comment]
Created [outline](https://github.com/bounswe/bounswe2024group8/wiki/Customer-Milestone-2-Presentation-Outline).

**Comment by yektaercul** [comment]
Implemented and presented seamlessly.
