### ISSUE TITLE
Unit Tests For Comment and File Services

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2024group8#388]
### Issue Description

I will implement these tests

### Issue Due Date

29/11/2024

### Reviewer

@oguzkagnici

### Revision Due Date

30/11/2024

**Comment by tuluyhansozen** [comment]
Completed @oguzkagnici

**Comment by oguzkagnici** [comment]
Written tests seem comprehensive for our use cases. Closing...
