### ISSUE TITLE
Unit tests for Tournament Service

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#389]
### Issue Description

I will write unit tests for our tournament service with at least of 70 percent line coverage rate.
<img width="688" alt="image" src="https://github.com/user-attachments/assets/d22758ae-b2ec-4a74-9ac4-946c23ee3e87">

### Issue Due Date

28/11/2024

### Reviewer

@tuluyhansozen

### Revision Due Date

29/11/2024

**Comment by yektaercul** [comment]
Created the tests and opened the [pr](https://github.com/bounswe/bounswe2024group8/pull/390)

**Comment by tuluyhansozen** [comment]
Pr closed
