### ISSUE TITLE
 Summary of customer feedback and reflections

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2024group8#391]
### Issue Description

I noted during the customer meeting. I will add them to wiki

### Issue Due Date

29/11/2024

### Reviewer

@onurcerli

### Revision Due Date

30/11/2024

**Comment by tuluyhansozen** [comment]
https://github.com/bounswe/bounswe2024group8/wiki/Second-Customer-Milestone-Report#51-summary-of-customer-feedback-and-reflections @onurcerli completed

**Comment by onurcerli** [comment]
It nicely summarizes both the customer's feedback on the project and the suggested solutions for the issues specified by the customer.
