### ISSUE TITLE
Backend - Implement Integration Test for backend

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#399]
### Issue Description

I will implement integration tests for important features of our backend

### Issue Due Date

10/12/2024

### Reviewer

@oguzkagnici

### Revision Due Date

11/12/2024

**Comment by yektaercul** [comment]
I have created a [pr](https://github.com/bounswe/bounswe2024group8/pull/447)

**Comment by oguzkagnici** [comment]
Written integration test seems comprehensive. Well done.
