### ISSUE TITLE
Backend - User search endpoint by similar username

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#404]
### Issue Description

User search endpoint with a given string query should be implemented.

### Issue Due Date

12/12/2024

### Reviewer

@yektaercul

### Revision Due Date

13/12/2024

**Comment by oguzkagnici** [comment]
Opened [pr](https://github.com/bounswe/bounswe2024group8/pull/414).

**Comment by yektaercul** [comment]
Works perfectly
