### ISSUE TITLE
Integration Test Scenarios for Backend

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2024group8#406]
### Issue Description

We will write Integration Test Scenarios for Backend

### Issue Due Date

9.12.2024

### Reviewer

@tuluyhansozen

### Revision Due Date

12.12.2024

**Comment by yektaercul** [comment]
One scenario explained here: [pr](https://github.com/bounswe/bounswe2024group8/pull/447)

**Comment by tuluyhansozen** [comment]
Scenario satisfies our needs for test
