### ISSUE TITLE
FE - W3C Annotation Protocol Research & Implementation

### ISSUE THREAD

**Issue by TurkerErdem99** [bounswe/bounswe2024group8#408]
### Issue Description

In order to achieve W3C Annotation Data Model Standard, we should research and implement annotation protocol that is defined in the standard. Related research should be done and implementation details may be added in this issue based on the research.

### Issue Due Date

10/12/2024 23:59

### Reviewer

@erselcanakcili

### Revision Due Date

10/12/2024 23:59

**Comment by TurkerErdem99** [comment]
Here are some related documents for further research:

- [Web Annotation Protocol](https://www.w3.org/TR/annotation-protocol/)
- [Web Annotation Data Model](https://www.w3.org/TR/annotation-model/#bib-annotation-protocol)

**Comment by deniz6221** [comment]
This issue was discarded
