### ISSUE TITLE
FE - W3C Annotation DB/Server Research & Implementation

### ISSUE THREAD

**Issue by TurkerErdem99** [bounswe/bounswe2024group8#409]
### Issue Description

In order to achieve W3C Annotation Data Model Standard, we should research and implement annotation DB and server separation that is defined in the standard. Related research should be done and implementation details may be added in this issue based on the research.

### Issue Due Date

10/12/2024 23:59

### Reviewer

@erselcanakcili

### Revision Due Date

10/12/2024 23:59

**Comment by deniz6221** [comment]
This issue was diccarded
