### ISSUE TITLE
Mobile - Annotation Implementation

### ISSUE THREAD

**Issue by TurkerErdem99** [bounswe/bounswe2024group8#410]
### Issue Description

Annotation feature shall be accessible on mobile application, based on the following requirements:

1.2.6.1 The system shall use annotations that comply with the W3C Web Annotation Data Model.
1.2.6.2 The system shall use annotations appearing in the form of a highlighted text.
1.2.6.3 The system shall allow annotations only in post bodies.

### Issue Due Date

10/12/2024 23:59

### Reviewer

@AliAlperenSonmez

### Revision Due Date

10/12/2024 23:59

**Comment by edonmez01** [comment]
Annotation viewing in posts has been implemented. In the post screen, annotated sections of the text are highlighted, and users can click on the highlighted sections to see a popup that includes the content of the annotation. Related PR: #440

**Comment by AliAlperenSonmez** [comment]
Annotations are well implemented for mobile.
