### ISSUE TITLE
Backend - Including post tags for search

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#415]
### Issue Description

I will be adding tag support to search, which enables users to find posts from their tags.

### Issue Due Date

10/12/2024

### Reviewer

@yektaercul

### Revision Due Date

10/12/2024

**Comment by oguzkagnici** [comment]
Opened [pr](https://github.com/bounswe/bounswe2024group8/pull/416).

**Comment by yektaercul** [comment]
Merged and tested, everything works...
