### ISSUE TITLE
Backend - Create new achievements

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#417]
### Issue Description

I will be creating/designing new achievements

### Issue Due Date

10/12/2024

### Reviewer

@yektaercul

### Revision Due Date

10/12/2024

**Comment by oguzkagnici** [comment]
Opened [pr](https://github.com/bounswe/bounswe2024group8/pull/418).

**Comment by yektaercul** [comment]
Merged the codes. Everything seems ok.
