### ISSUE TITLE
Backend - Delete/Edit Posts

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#419]
### Issue Description

I will be writing endpoints for deleting and editing own posts.

### Issue Due Date

10/12/2024

### Reviewer

@yektaercul

### Revision Due Date

10/12/2024

**Comment by oguzkagnici** [comment]
Opened [pr](https://github.com/bounswe/bounswe2024group8/pull/441).

**Comment by yektaercul** [comment]
Gave feedback, tested again, all perfect.
