### ISSUE TITLE
Research related to practice project

### ISSUE THREAD

**Issue by onurcerli** [bounswe/bounswe2024group8#42]
I will firstly conduct a research about web application development in order to get familiarize with the web development concepts and if I get the chance I will also try to prepare for topics below:
* Wikidata, Wikidapa API, etc.
* Application Programming Interface (API) use and development

As I make progress, I will update the issue and share my findings.

**Comment by onurcerli** [comment]
I made a research about what web development is, and also watched the video in the [link](https://www.youtube.com/watch?v=ciz2UaifaNM) and some other videos to get an understanding of what html, css and javascript do. I also created the page [Web Application Development](https://github.com/bounswe/bounswe2024group8/wiki/Web-Application-Development) and added some introductory information about web development. I am keeping the issue open for now as I might make further research on the topic or on the other topics I mentioned in the previous comment.

**Comment by yektaercul** [comment]
All of the research are done so I am closing the issue
