### ISSUE TITLE
Writing Lab 9 Report

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#420]
### Issue Description

I will be writing the report for Lab 9

### Issue Due Date

10/12/2024

### Reviewer

@yektaercul

### Revision Due Date

10/12/2024

**Comment by oguzkagnici** [comment]
Created the [report](https://github.com/bounswe/bounswe2024group8/wiki/Lab-9-Report)

**Comment by yektaercul** [comment]
Concise and well-explained report
