### ISSUE TITLE
FE - Search User and Search Pagination 

### ISSUE THREAD

**Issue by TurkerErdem99** [bounswe/bounswe2024group8#427]
### Issue Description

Search results page should be updated, so that:

- [ ] Posts in the search results are paginated
- [ ] Users should be listed in a different tab in search results page

### Issue Due Date

14/12/2024 19:00

### Reviewer

@deniz6221

### Revision Due Date

14/12/2024 19:00

**Comment by TurkerErdem99** [comment]
Implementation is completed, PR #428 is ready to be merged.

**Comment by deniz6221** [comment]
PR got merged successfully
