### ISSUE TITLE
Decidinge New Format of Create Post Page

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2024group8#429]
### Issue Description

According to the customer meeting 2 feedback, we will prove new fields in create post page.

### Issue Due Date

15.12.2024

### Reviewer

@deniz6221

### Revision Due Date

15.12.2024

**Comment by tuluyhansozen** [comment]
https://github.com/bounswe/bounswe2024group8/wiki/Post-Creation-Page i added @deniz6221

**Comment by oguzkagnici** [comment]
I have conducted a research and came up with the [document](https://kcad.ferris.edu/uploads/docs/elements_principles_3D.pdf), which contains several fields regarding 3d modeling.

**Comment by deniz6221** [comment]
Frontend team implemented this format, closing
