### ISSUE TITLE
FE - Profile Page Improvements

### ISSUE THREAD

**Issue by TurkerErdem99** [bounswe/bounswe2024group8#430]
### Issue Description

Profile page should be changed/improved, so that the following items can be done in the profile page:

- [x] Edit avatar, by clicking on the avatar
- [x] Change password, with a new button for this purpose
- [x] Direct navigation to own profile, by changing the structure of the profile button which is located on the page header
- [x] Pagination of posts in the profile page

### Issue Due Date

14/12/2024 20:00

### Reviewer

@TurkerErdem99

### Revision Due Date

14/12/2024 20:00

**Comment by deniz6221** [comment]
PR got merged successfully
