### ISSUE TITLE
FE - Post Form Structure Implementation

### ISSUE THREAD

**Issue by TurkerErdem99** [bounswe/bounswe2024group8#434]
### Issue Description

Gallery Posts should contain technical details and design features from now on. So, when a user creates a new gallery post, they should be able to put related fields, as described [here](https://github.com/bounswe/bounswe2024group8/wiki/Post-Creation-Page).

### Issue Due Date

14/12/2024 23:00

### Reviewer

@erselcanakcili

### Revision Due Date

14/12/2024 23:00

**Comment by deniz6221** [comment]
We have implemented the form for Create Post component and merged this [PR](https://github.com/bounswe/bounswe2024group8/pull/435) , closing

**Comment by yektaercul** [comment]
I have provided a suggestion on how to implement the form structure in a way that enables us to not change anything on backend structure by using delimiters when getting and posting Post bodies. I have contributed via Whatsapp.
