### ISSUE TITLE
Mobile - Implement post body parse/join for updated body format

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#438]
### Issue Description

The parse and join methods for the updated post body format will be implemented. The methods will use the ampersand character (&) as the delimiter.

### Issue Due Date

15/12/2024 22:00

### Reviewer

@AliAlperenSonmez

### Revision Due Date

15/12/2024 22:00

**Comment by edonmez01** [comment]
The implementation is complete. Related PR: #439

**Comment by AliAlperenSonmez** [comment]
Implementation of post body parse for updated body format is solid.
