### ISSUE TITLE
Create Requirements page for the project

### ISSUE THREAD

**Issue by daghanerdonmez** [bounswe/bounswe2024group8#44]
### Issue Description

We need a clear, unambiguous and complete requirements documentation. It also needs to be consistent and modifiable in the future. We have already talked about what it should look like and wrote a draft in the meeting with some of my teammates. I have to write it in compliance with the properties I've mentioned above.

### Issue Due Date

14.03.2024

### Reviewer

@yektaercul

### Revision Due Date

15.03.2024

**Comment by edonmez01** [comment]
The requirements page is created [here](https://github.com/bounswe/bounswe2024group8/wiki/Requirements).

**Comment by daghanerdonmez** [comment]
Done, see the [page]([here](https://github.com/bounswe/bounswe2024group8/wiki/Requirements))

**Comment by yektaercul** [comment]
I have reopend this issue cause I need some refactoring could be made as the followings:
Should add to glossary:
system-admin: Can delete any comment/post. Can only post/comment if they are the member of that community or its a non-community post/comment.
Can change their team as much as they want.

Also we can add non-community to the glossary.

1.1.2.2.1
Should add:
Change the team they support once they've chosen it.
Can follow other users
Can delete a follower.

1.1.2.2 Users shall not be able to and 1.1.3 Communities (See "1.2.1 Communities")
When signing up, users will be asked about their favorite team, but they have the option to skip selecting one. However, they should only have one chance to select their favorite team from their profile later if they haven't done so before. Once they select their favorite team, they will automatically join its community, but they can opt out of the community if they wish. If they want, they can rejoin the same community later, provided they have that team as favorite team selected.

1.2.2.5 One of the tags shall be the community in which the post is posted.
In its implementation we must not give a choice to the user. This tag will be added regardlessly. That is a must. Posts that are not a part of community will be tagged as non-community. This will ease the making of filter mechanism.


1.1.4.5 If a post is in the users' team's community users shall be able to and
This should be updated as can dislike or like any post that is a non-community post or a post which is posted in a community that the user is a member of.

1.1.5.5 Users shall be able to like or dislike a comment if that comment belongs to the community of the team they support.

This should be updated as can dislike or like any comment that belongs to a non-community post or a comment in a post which is posted in a community that the user is a member of.

1.1.6.1 if it's private only the followers can see . If it's not private everybody can see including guests.

1.2:
1.2.2.1: great idea (we should ask to the customer if this titles can be searched with semantic searching.)


1.2.6.1.3.3: This could be hard to implement so we should delete this I guess.

**Comment by daghanerdonmez** [comment]
Some changes are made according to your review, I've not changed some ambigous parts to avoid making the requirements contradict itself. Small details must be talked during weekly meeting at 21.04.2024.
