### ISSUE TITLE
Backend - Writing unit tests for Wikidata Service

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#443]
### Issue Description

I will be writing unit test for Wikidata Service and several other services

### Issue Due Date

20/12/2024

### Reviewer

@yektaercul

### Revision Due Date

20/12/2024

**Comment by oguzkagnici** [comment]
I have written 3 unit tests for Wikidata service and 2 for post service

**Comment by yektaercul** [comment]
All works perfectly
