### ISSUE TITLE
FE - Annotation Improvement

### ISSUE THREAD

**Issue by erselcanakcili** [bounswe/bounswe2024group8#454]
### Issue Description

Users will annotate more easily with the new improvements. The annotations sidebar UI will be redesigned for better usability and user experience.

### Issue Due Date

16/12/2024 21:59

### Reviewer

@erselcanakcili

### Revision Due Date

16/12/2024 21:59

**Comment by deniz6221** [comment]
Improvement Completed, closing the issue.
