### ISSUE TITLE
Mobile - Enhancing leaderboard screen

### ISSUE THREAD

**Issue by AliAlperenSonmez** [bounswe/bounswe2024group8#460]
### Issue Description

Leaderboard screen should be enhanced with links to profiles and posts. User profile photos should be added as well.

### Issue Due Date

15/12/2024

### Reviewer

@onurcerli

### Revision Due Date

15/12/2024

**Comment by AliAlperenSonmez** [comment]
Leaderboard screen is enhanced and completed.

**Comment by onurcerli** [comment]
Implementation is solid and works as intended. Closing the issue...
