### ISSUE TITLE
Creating Customer Milestone 3 Presentation Outline

### ISSUE THREAD

**Issue by AliAlperenSonmez** [bounswe/bounswe2024group8#461]
### Issue Description

Presentation outline for the customer milestone 3 should be created.

### Issue Due Date

15/12/2024

### Reviewer

@yektaercul 

### Revision Due Date

15/12/2024

**Comment by AliAlperenSonmez** [comment]
[Presentation outline](https://github.com/bounswe/bounswe2024group8/wiki/Customer-Milestone-3-Presentation-Outline) is created.

**Comment by yektaercul** [comment]
It is a basic outline which will not be enough for us. Here is the refactored one created by @oguzkagnici in the issue [here](https://github.com/bounswe/bounswe2024group8/issues/444) .

**Comment by yektaercul** [comment]
Final outline is here created by @oguzkagnici . [Outline](https://github.com/bounswe/bounswe2024group8/wiki/Final-Customer-Milestone-Presentation-Outline)
