### ISSUE TITLE
Creating Scenario for Functionality Exhibition 

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2024group8#464]
### Issue Description

I will write scenario for Functionality Exhibition 

### Issue Due Date

20.12.2024

### Reviewer

@edonmez01

### Revision Due Date

20.12.2024

**Comment by tuluyhansozen** [comment]
https://github.com/bounswe/bounswe2024group8/wiki/User-Scenario @edonmez01

**Comment by edonmez01** [comment]
Nicely done.
