### ISSUE TITLE
Backend - Hotfix: Add permanent file links and configure CORS for bucket file service. 

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#465]
### Issue Description

File service generates temporary links for now and I will fix them to return permanent links.

### Issue Due Date

09/12/2024

### Reviewer

@oguzkagnici

### Revision Due Date

09/12/2024

**Comment by yektaercul** [comment]
I have fixed the url in this [commit](https://github.com/bounswe/bounswe2024group8/commit/c7f8b317af3cdc36975416b85ffb89452e2e7ff3) and configured the CORS in our deployment provider GCP.

**Comment by oguzkagnici** [comment]
Everything seems properly working. Closing the issue.
