### ISSUE TITLE
Create some possible user scenarios

### ISSUE THREAD

**Issue by onurcerli** [bounswe/bounswe2024group8#47]
### Issue Description

I will create scenarios page in the wiki and write some possible user scenarios such as user registration and login.

### Issue Due Date

16/03/2024

### Reviewer

@yektaercul

### Revision Due Date

16/03/2024

**Comment by onurcerli** [comment]
I created [Scenarios](https://github.com/bounswe/bounswe2024group8/wiki/Scenarios) page and added 5 scenarios. After review, we can make updates or/and add more scenarios if necessary.

**Comment by yektaercul** [comment]
@onurcerli 
These little fixes should be made:
1 - User Registration and Login
safeguard his account. After registering the platform->safeguard his account. Now the only part left is to verify his account by email then he can regiser freely. After that

2 - Updating Account Information
support for Galatasaray. Pleased with her updates -> support for Galatasaray. And lastly she decides to make her profile private meaning that she only wants her followers to see detailed information about her . Pleased with her updates

When Requirements are refactored also the acceptence criteria should be updated accordingly with these new steps.

Others are seamless. Thanks for your work.

**Comment by yektaercul** [comment]
-Now the only part left is to verify his account by email then he can register freely. In the first scenario should be deleted.

-alatasaray and lastly she decides to make her profile private meaning that she only wants her followers to see detailed information about her. Should be deleted from the second Scenario

In Scenario 5 all the parts related to the account deletion should be erased. We won't implement any email service so there won't be any notifications or password resets.

Please update the scenarios accordingly

**Comment by onurcerli** [comment]
Updated the [page](https://github.com/bounswe/bounswe2024group8/wiki/Scenarios) according to the feedback. Removed the 5th scenario completely because it is directly about recovering and deleting account, and we will not be implementing these features

**Comment by yektaercul** [comment]
It seems in accordance with our requirements so I am closing this issue.
