### ISSUE TITLE
Creating Customer Milestone 1 Report

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#51]
### Issue Description

Creating first customer milestone for various deliverables.

### Issue Due Date

18/03/2024

### Reviewer

@yektaercul @daghanerdonmez 

### Revision Due Date

18/03/2024

**Comment by yektaercul** [comment]
Added the Decision-making and Assessment part as you can see in [this page](https://github.com/bounswe/bounswe2024group8/wiki/Milestone-1-Report) .

**Comment by daghanerdonmez** [comment]
I have reviewed and improved the Summary and Status parts. I have added a contribution table for the members to add their contributions. I have created a table about the status of the deliverables.

**Comment by yektaercul** [comment]
Added the Personal Contribution of my own part as you can see in https://github.com/bounswe/bounswe2024group8/issues/54 .

**Comment by oguzkagnici** [comment]
Added Summary and Evaluation sections, which can be seen in #60 and #61
