### ISSUE TITLE
Plan and add future milestones to the Roadmap

### ISSUE THREAD

**Issue by daghanerdonmez** [bounswe/bounswe2024group8#53]
### Issue Description

To be able to plan what and when to do in the future, we need to have a clear roadmap with a good scheduling. We have already prepared a roadmap with the issues we have done so far. I will plan our future work and put it on our roadmap as draft issues.

### Issue Due Date

19.03.2024

### Reviewer

@yektaercul

### Revision Due Date

19.03.2024

**Comment by yektaercul** [comment]
Reviewed your work. Added more future bullet points on Frontend and Backend developments and edited their estimated durations in accordance. It seems done for now so I am closing the issue
