### ISSUE TITLE
Add personal contributions to Contribution Table in Milestone Report

### ISSUE THREAD

**Issue by yektaercul** [bounswe/bounswe2024group8#54]
### Issue Description

I will add explanatory assessment on what I have done during the whole course of the project  to the [Milestone 1 Report](https://github.com/bounswe/bounswe2024group8/wiki/Milestone-1-Report) .

### Issue Due Date

03/19/2024

### Reviewer

@oguzkagnici 

### Revision Due Date

03/19/2024

**Comment by oguzkagnici** [comment]
Looks detailed and sufficient.
