### ISSUE TITLE
Add personal contributions to Contribution Table in Milestone Report

### ISSUE THREAD

**Issue by daghanerdonmez** [bounswe/bounswe2024group8#55]
### Issue Description

I will add explanatory assessment on what I have done during the whole course of the project to the [Milestone 1 Report](https://github.com/bounswe/bounswe2024group8/wiki/Milestone-1-Report).

### Issue Due Date

19.03.2024

### Reviewer

@daghanerdonmez

### Revision Due Date

19.03.2024

**Comment by yektaercul** [comment]
Seems very fit to our needs. Closing the issue
