### ISSUE TITLE
Add personal contributions to Contribution Table in Milestone Report

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#59]
### Issue Description

I will summarize my work so far and fill the table accordingly

### Issue Due Date

19/03/2024

### Reviewer

@yektaercul 

### Revision Due Date

19/03/2024

**Comment by oguzkagnici** [comment]
Added my contributions to the [contribution table](https://github.com/bounswe/bounswe2024group8/wiki/Milestone-1-Report#3-contribution-table)

**Comment by yektaercul** [comment]
Seems fit to criteria so I am closing this issue.
