### ISSUE TITLE
Add personal contributions to Contribution Table in Milestone Report 

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#62]
### Issue Description

I will add my personal contribution to the contribution table in the [Milestone 1 Report](https://github.com/bounswe/bounswe2024group8/wiki/Milestone-1-Report).

### Issue Due Date

19/03/2024

### Reviewer

@erselcanakcili

### Revision Due Date

19/03/2024

**Comment by edonmez01** [comment]
Added my contribution to the [contribution table](https://github.com/bounswe/bounswe2024group8/wiki/Milestone-1-Report#3-contribution-table).

**Comment by erselcanakcili** [comment]
I saw your work which is fine. Closing the issue.
