### ISSUE TITLE
Create use case diagram

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#68]
### Issue Description

I will create a use case diagram for the project.

### Issue Due Date

16/04/2024, 00:00

### Reviewer

@CotSezer

### Revision Due Date

17/04/2024, 00:00

**Comment by edonmez01** [comment]
I created a use case diagram on draw.io. I uploaded the diagram to its dedicated page in the wiki [here](https://github.com/bounswe/bounswe2024group8/wiki/Use-Case-Diagram). I also added the link to the wiki sidebar.

**Comment by CotSezer** [comment]
I examined the use case diagram. Considering the requirements and elicitations, I think it is appropriate except for the addition of the following situations:

View profile <- - - - -<<extend>>- - - - - Share profile
View profile <- - - - -<<extend>>- - - - - Block user
Write comment <- - - - -<<extend>>- - - - - Edit comment
View comment <- - - - -<<extend>>- - - - - Share comment
View community <- - - - -<<extend>>- - - - - Unsubscribe from the community View post <- - - - -<<extend>>- - - - - Share post

**Comment by edonmez01** [comment]
I added a use case for unsubscribing from a community, as you pointed out.

I don't think we have any requirements that lead to any of the other use cases that you mentioned (please correct me if I'm wrong). Would it be correct to add such use cases to the diagram?

**Comment by CotSezer** [comment]
I think you are right, it is not explicitly stated. It's OK.
