### ISSUE TITLE
Conduct research on Git

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#69]
### Issue Description

I will carry out some research about the useful functionalities of Git, and I will document my findings in the project's wiki.

### Issue Due Date

16/04/2024, 00:00

### Reviewer

@yektaercul

### Revision Due Date

17/04/2024, 00:00

**Comment by edonmez01** [comment]
I completed my research and recorded my findings in the wiki [here](https://github.com/bounswe/bounswe2024group8/wiki/Git). I also added the link to the wiki sidebar.

**Comment by yektaercul** [comment]
That wiki page seems well written and complete thus I am closing this issue
