### ISSUE TITLE
Creating Sequence Diagrams

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#70]
### Issue Description

Starting to create sequence diagrams for different functions.

### Issue Due Date

21/04/2024 20:00

### Reviewer

@yektaercul

### Revision Due Date

22/04/2024 23:00

**Comment by oguzkagnici** [comment]
Created sequence diagrams for post and comment functions.

**Comment by yektaercul** [comment]
Seems very detailed and well-designed. There is no problem so I am closing this issue
