### ISSUE TITLE
Implementing Backend for MVP

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#72]
### Issue Description

Starting to implement backend for MVP

### Issue Due Date

29/04/2024 23:00

### Reviewer

@yektaercul

### Revision Due Date

29/04/2024 23:00

**Comment by CotSezer** [comment]
i pushed [backend-init](https://github.com/bounswe/bounswe2024group8/tree/main/application/fanatic-backend)

**Comment by oguzkagnici** [comment]
created Wikidata and post service [#111 ].

**Comment by yektaercul** [comment]
initialization seems okay. Needed changes like wrong or missing dependencies. Also .gitignore was missing. All of these are refactored and pushed again.
