### ISSUE TITLE
Login and Registration Pages For Mobile

### ISSUE THREAD

**Issue by deniz6221** [bounswe/bounswe2024group8#74]
### Issue Description

Implement login and registration pages for the mobil app

### Issue Due Date

28/04/2024

### Reviewer

@deniz6221

### Revision Due Date

28/04/2024

**Comment by onurcerli** [comment]
added the initial files with login and registration screens under [mobile](https://github.com/bounswe/bounswe2024group8/tree/main/application/mobile) folder. logic part for these screens are not complete yet

**Comment by edonmez01** [comment]
All features for the login and registration pages are implemented. Closing the issue.
