### ISSUE TITLE
Learn React Native

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#76]
### Issue Description

I am going to start learning React Native (which I have no previous experience with) by following the [official guide](https://reactnative.dev/docs/getting-started).

### Issue Due Date

28/04/2024, 00:00

### Reviewer

@edonmez01

### Revision Due Date

28/04/2024, 00:00

**Comment by supolaris** [comment]
Keep going

**Comment by edonmez01** [comment]
Even though the learning process never ends, I am closing the issue as we have delivered our final milestone.
