### ISSUE TITLE
Create a login page for the web app.

### ISSUE THREAD

**Issue by daghanerdonmez** [bounswe/bounswe2024group8#79]
### Issue Description

A login page need to be created for the web application. It will have the features specified in the requirements [here](https://github.com/bounswe/bounswe2024group8/wiki/Requirements).

### Issue Due Date

27.04.2024

### Reviewer

@daghanerdonmez 

### Revision Due Date

28.04.2024

**Comment by erselcanakcili** [comment]
I created a login page and sign up page as stated in the requirements.

**Comment by erselcanakcili** [comment]
Made the API connection of backend and frontend. Hence login page works exactly as desired in the design.
